name: weev
description: Developer motivation CLI â€“ unify coding activity across platforms
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.2
  http: ^1.2.1
  path: ^1.9.0
  html: ^0.15.4
  chalkdart: ^3.0.5 # or latest
  # table: ^0.0.1-dev # simple tables
  # console_bars: ^ # progress bars

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
